n1 = int(input('Digite um valor: '))
n2 = int(input('Digite outro valor: '))
print('A soma vale {}' .format(n1+n2))
print('A divisão vale {:.3f}' .format(n1/n2))
print('A multiplicação vale {}' .format(n1*n2))
print('A potencia vale {}' .format(n1**n2))
print('A a divisão inteira vele {}' .format(n1 // n2))
